title: Laboratorio Virtual para las Ciencias Cognitivas y del Comportamiento
description: Proyecto PAPIME; Laboratorio 25

#baseurl: "/cayman-blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
#url: "https://lorepirri.github.io" # change this to the base hostname & protocol for your site

# social
#author: "Lore Pirri"
#image: /thumbnail-jumbo.png
#twitter:
#  username: lorepirri
#  site:
#facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  #app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:

theme: jekyll-theme-cayman
